version: "2"
services:
    backend:
        build: ./backend
        restart: always
        ports:
            - "5000:5000"
        working_dir: /backend
        volumes:
            - ./backend:/backend
            - /backend/node_modules
        depends_on:
            - mongodb
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        volumes:
            - ./data-node:/data/db
        ports:
            - 5000:5000
        command: mongod --noauth